### ISSUE TITLE
About the python version

### ISSUE THREAD

**Issue by jzbbobo** [marcellacornia/mlnet#3]
Hi, marcella.
when I used this net to train my own dataset, something wrong like below:

``` conslole
Compile ML-Net Model
Training ML-Net
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    ModelCheckpoint('weights.mlnet.{epoch:02d}-{val_loss:.4f}.pkl', save_best_only=True)])
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 1343, in fit_generator
    self._make_train_function()
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 695, in _make_train_function
    self.constraints,
  File "/usr/lib64/python2.7/site-packages/keras/engine/topology.py", line 1948, in constraints
    for key, value in layer.constraints.items():
AttributeError: 'list' object has no attribute 'items'
```

the python version about my machine is 2.7 .

**Comment by marcellacornia** [comment]
Hi @jzbbobo, this problem is due to the new version of keras.
In the latest version, the layer constraints syntax has been changed.

I've just updated the eltwise product layer. Now it should work.

**Comment by jzbbobo** [comment]
It works now, thanks for your help.
